name: 06b variables y numero aleatorio
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  tirada-dados:
    runs-on: ubuntu-latest
    steps:
      - name: Generar nÃºmero aleatorio
        run: echo "NUM_ALEATORIO=$((1 + RANDOM % 6))" >> "$GITHUB_ENV"
       # Escapar : usando format
       # - name: Leer resultado
       #   run: echo ${{format('El valor del dado es{0} {1}', ':', env.NUM_ALEATORIO)}}
       #  Escapar : usando cadena de texto multininea
      - name: Leer resultado
        run: |
          echo "El valor del dado es: ${{env.NUM_ALEATORIO }}" 
