name: 09a - Cache
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Asignar versi√≥n de node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - uses: actions/cache@v4
        id: cache
        with:
          # path: ~/ .npm
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**package-lock.json')}}
      - name: Instalar dependencias
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lanzar pruebas
        run: npm test